routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/',[HomeController::class,'index'])->name('home');
Route::resource('category',CategoryController::class);
Route::resource('products',ProductController::class);
Route::resource('roles',RoleController::class);
Route::resource('users',UserController::class);


Route::get('product/{category_id}', [ClientProductController::class, 'category_product'])->name('client.products.categoryid');
Route::get('product-detail/{id}', [ClientProductController::class, 'show'])->name('client.product.show');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Permission\Models\Role as ModelsRole;

class Role extends ModelsRole
{
    use HasFactory;

    protected $fillable = [
        'name',
        'display_name',
        'group',
        'guard_name'
    ];
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Role\CreateRoleRequest;
use App\Http\Requests\Role\UpdateRoleRequest;
use App\Models\Permission;
use App\Models\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    protected $role;
    protected $permission;
    public function __construct(Role $role, Permission $permission)
    {
        $this->role = $role;
        $this->permission = $permission;
    }


    public function index(Request $request)
    {
        $search = $request->get(key: 'q');

        $roles = $this->role->latest('id')->where(column: 'name', operator: 'like', value: '%' . $search . '%')->paginate(3);
        return view('admin.roles.index', compact('roles', 'search'));
    }
    public function create()
    {
        $permissions = $this->permission->all()->groupBy('group');

        return view('admin.roles.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateRoleRequest $request)
    {
        $dataCreate = $request->all();
        $dataCreate['guard_name'] = 'web';
        $role = $this->role->create($dataCreate);
        $role->permissions()->attach($dataCreate['permission_ids']);
        return redirect()->route('roles.index')->with(['message' => 'create role success']);
    }
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $role = $this->role->with('permissions')->findOrFail($id);
        $permissions = $this->permission->all()->groupBy('group');

        return view('admin.roles.edit', compact('permissions', 'role'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateRoleRequest $request, string $id)
    {
        $role = $this->role->findOrFail($id);
        $dataUpdate = $request->all();
        $role->update($dataUpdate);
        $role->permissions()->sync($dataUpdate['permission_ids']);
        return redirect()->route('roles.index')->with(['message' => 'update role success']);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $this->role->destroy($id);
        return redirect()->route('roles.index')->with(['message' => 'delete role success']);
    }
}

resources/views/admin/roles/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Create Role')
@section('content')
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">CREATE ROLE</h4>
            <p class="card-description">
                Back
            </p>
            <form class="forms-sample" method="post" action="{{ route('roles.store') }}">
                @csrf
                @method('POST')
                <div class="form-group">
                    <label for="exampleInputUsername1">Name</label>
                    <input type="text" class="form-control" id="exampleInputUsername1" placeholder="NameRole"
                        name="name">
                    @error('name')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="exampleInputDisplayName1">DisplayName</label>
                    <input type="text" class="form-control" id="exampleInputDisplayName1" placeholder="DisplayName"
                        name="display_name">
                    @error('display_name')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="exampleInputDisplayName1">Group</label>
                    <select class="form-control form-control-sm" id="exampleFormControlSelect3" name="group">
                        <option value="">Choose</option>
                        <option value="system">System</option>
                        <option value="user">User</option>
                    </select>
                    @error('group')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="form-group">
                    <div class="row">
                        @foreach ($permissions as $groupName => $permission)
                            <div class="col-md-2">
                                <h4>{{ $groupName }}</h4>
                                @foreach ($permission as $item)
                                    <div class="col form-check form-check-success">

                                        <label class="form-check-label">
                                            <input type="checkbox" class="form-check-input" value="{{ $item->id }}"
                                                name="permission_ids[]">
                                            {{ $item->display_name }}
                                            <i class="input-helper"></i>
                                        </label>
                                    </div>
                                @endforeach
                            </div>
                        @endforeach
                    </div>

                </div>

                <button class="btn btn-primary mr-2">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Edit Role')
@section('content')
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">EDIT ROLE</h4>
            <p class="card-description">
                Back
            </p>
            <form class="forms-sample" method="post" action="{{ route('roles.update', $role->id) }}">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="exampleInputUsername1">Name</label>
                    <input type="text" class="form-control" id="exampleInputUsername1" placeholder="NameRole"
                        name="name" value="{{ old('name') ?? $role->name }}">
                    @error('name')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="exampleInputDisplayName1">DisplayName</label>
                    <input type="text" class="form-control" id="exampleInputDisplayName1" placeholder="DisplayName"
                        name="display_name" value="{{ old('display_name') ?? $role->display_name }}">
                    @error('display_name')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="exampleInputDisplayName1">Group</label>
                    <select class="form-control form-control-sm" id="exampleFormControlSelect3" name="group">
                        <option value="">Choose</option>
                        <option value="system" {{ $role->group == 'system' ? 'selected' : '' }}>System</option>
                        <option value="user" {{ $role->group == 'user' ? 'selected' : '' }}>User</option>
                    </select>
                    @error('group')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <div class="row">
                        @foreach ($permissions as $groupName => $permission)
                            <div class="col-md-2">
                                <h4>{{ $groupName }}</h4>
                                @foreach ($permission as $item)
                                    <div class="col form-check form-check-success">

                                        <label class="form-check-label">
                                            <input type="checkbox" class="form-check-input" value="{{ $item->id }}"
                                                name="permission_ids[]"
                                                {{ $role->permissions->contains('name', $item->name) ? 'checked' : '' }}>
                                            {{ $item->display_name }}
                                            <i class="input-helper"></i>
                                        </label>
                                    </div>
                                @endforeach
                            </div>
                        @endforeach
                    </div>
                </div>
                <button class="btn btn-primary mr-2">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Roles')


@section('content')
    <div class="card">
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        <div class="card-body">
            <h4 class="card-title">ROLE</h4>
            <div class="pull-right mb-2">
                <a class="btn btn-success" href="{{ route('roles.create') }}"> New role</a>
            </div>
            <div class="table-responsive pt-3">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                DisplayName
                            </th>
                            <th>
                                Group
                            </th>
                            <th>
                                Action
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($roles as $item)
                            <tr>
                                <td>
                                    {{ $item->id }}
                                </td>
                                <td>
                                    {{ $item->name }}
                                </td>
                                <td>
                                    {{ $item->display_name }}
                                </td>
                                <td>
                                    {{ $item->group }}
                                </td>

                                <td>
                                    <div class="row">
                                        <div class="p-1">
                                            <form action="{{ route('roles.destroy', $item->id) }}" method="post">
                                                <a href="{{ route('roles.edit', $item->id) }}"
                                                    class="btn btn-info btn-fw">Update</a>
                                                @csrf
                                                @method('delete')
                                                <button class="btn btn-danger">Delete</button>
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach

                    </tbody>
                </table>
                <div class="btn-group mt-1" role="group" aria-label="Basic example">
                    {{ $roles->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection