routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/',[HomeController::class,'index'])->name('home');
Route::resource('category',CategoryController::class);
Route::resource('products',ProductController::class);
Route::resource('roles',RoleController::class);
Route::resource('users',UserController::class);


Route::get('product/{category_id}', [ClientProductController::class, 'category_product'])->name('client.products.categoryid');
Route::get('product-detail/{id}', [ClientProductController::class, 'show'])->name('client.product.show');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/layouts/sidebar.blade.php
 <!-- partial:partials/_sidebar.html -->
 <nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
      <li class="nav-item">
        <a class="nav-link" href="index.html">
          <i class="mdi mdi-grid-large menu-icon"></i>
          <span class="menu-title">Dashboard</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('roles.index')}}">
          <i class="mdi mdi-account-key menu-icon"></i>
          <span class="menu-title">Roles</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('products.index')}}">
          <i class="mdi mdi-carrot menu-icon"></i>
          <span class="menu-title">Product</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('category.index')}}">
          <i class="mdi mdi-cards-playing-outline menu-icon"></i>
          <span class="menu-title">Category</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="index.html">
          <i class="mdi mdi-cart-outline menu-icon"></i>
          <span class="menu-title">Cart</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="index.html">
          <i class="mdi mdi-cart-plus menu-icon"></i>
          <span class="menu-title">Order</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="index.html">
          <i class="mdi mdi-comment-text-outline menu-icon"></i>
          <span class="menu-title">Comment</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('users.index')}}">
          <i class="mdi mdi-account-multiple-outline menu-icon"></i>
          <span class="menu-title">User</span>
        </a>
      </li>
    
    </ul>
  </nav>