routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/',[HomeController::class,'index'])->name('home');
Route::resource('category',CategoryController::class);
Route::resource('products',ProductController::class);
Route::resource('roles',RoleController::class);
Route::resource('users',UserController::class);


Route::get('product/{category_id}', [ClientProductController::class, 'category_product'])->name('client.products.categoryid');
Route::get('product-detail/{id}', [ClientProductController::class, 'show'])->name('client.product.show');
Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'id',
        'name',
        'image',
        'price',
        'description',
        'category_id'
    ];

    public function details()
    {
        return $this->hasMany(ProductDetail::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    public function getBy($dataSearch, $categoryId)
    {
        return $this->whereHas('category', fn ($q) => $q->where('category_id', $categoryId))->paginate(3);
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductDetail;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    protected $category;
    protected $product;
    protected $productDetail;

    public function __construct(Product $product, Category $category, ProductDetail $productDetail)
    {
        $this->product = $product;
        $this->category = $category;
        $this->productDetail = $productDetail;
    }
    public function index(Request $request)
    {
        $search = $request->get(key:'q');
        $products = $this->product->latest('id')->where(column:'name', operator:'like', value:'%'.$search.'%')->paginate(3);
        $products->load('category');
        return view('admin.product.index', compact('products','search'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories = $this->category->get(['id', 'name']);
        return view('admin.product.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $dataCreate = $request->except('sizes');
        $sizes = $request->sizes ? json_decode($request->sizes) : [];
        $dataCreate['image'] = $request->file('image')->getClientOriginalName(); //lay ten file
        $request->file('image')->storeAs('public/images', $dataCreate['image']); //luu file vao duong dan public/images voi ten $logo

        $product = $this->product->create($dataCreate); //tao ban ghi co du lieu la $data
        $sizeArray = [];
        foreach ($sizes as $size) {
            $sizeArray[] = ['size' => $size->size, 'quantity' => $size->quantity, 'product_id' => $product->id];
        }
        $this->productDetail->insert($sizeArray);
        return redirect()->route('products.index')->with('success', 'Product has been created successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $product = $this->product->with(['details', 'category'])->findOrFail($id);
        $product->description = htmlspecialchars_decode($product->description);

        return view('admin.product.show', compact('product'));
    }
    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $product = $this->product->with(['details', 'category'])->findOrFail($id);

        $categories = $this->category->get(['id', 'name']);
        return view('admin.product.edit', compact('categories','product'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $dataUpdate = $request->except('sizes');
        $sizes = $request->sizes ? json_decode($request->sizes) : [];
        $product = $this->product->findOrFail($id);
        if ($request->file('image') !== null) {
            $dataUpdate['image'] = $request->file('image')->getClientOriginalName(); //lay ten file
            $request->file('image')->storeAs('public/images',   $dataUpdate['image']); //luu file vao duong dan public/images voi ten $image
        }
        $product->update( $dataUpdate); //tao ban ghi co du lieu la $data
        
        $sizeArray = [];
        foreach ($sizes as $size) {
            $sizeArray[] = ['size' => $size->size, 'quantity' => $size->quantity, 'product_id' => $product->id];
        }
        $product->details()->delete();
        $this->productDetail->insert($sizeArray);
        return redirect()->route('products.index')->with('success', 'Product has been updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Product $product)
    {
        $product->delete();

        return redirect()->route('products.index')
            ->with('success', 'Delete products successfully');
    }
}

app/Http/Controllers/Client/ProductController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    protected $product;
    public function __construct(Product $product)
    {
        $this->product = $product;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = $this->product->latest('id')->paginate(5);

        return view('client.shop.index', compact('products'));
    }

    public function category_product(Request $request, $category_id)
    {
        $products = $this->product->getBy($request->all(), $category_id);
        return view('client.shop.index', compact('products'));
    }
    public function show($id)
    {
        $product = $this->product->with('details')->findOrFail($id);
        $categoryId = $product->category->pluck('id')->first(); // Assuming a product can belong to multiple categories, we retrieve the first category ID.

        $relatedProducts = $this->product->getBy($product->name, $categoryId);

        return view('client.shop.detail', compact('product', 'relatedProducts'));
    }
}

resources/views/admin/product/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Create Product')
@section('content')
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">CREATE PRODUCT</h4>
                    <p class="card-description">

                    </p>
                    <form class="forms-sample" method="post" action="{{ route('products.store') }}" enctype="multipart/form-data">
                        @csrf
                        @method('POST')
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-6">
                                    <label>Avata</label>
                                    <input type="file" name="image" accept="image/*" id="image-input"
                                        class="file-upload-default">
                                    <div class="input-group col-xs-6">
                                        <input type="text" class="form-control file-upload-info" disabled=""
                                            placeholder="Upload Image">
                                        <span class="input-group-append">
                                            <button class="file-upload-browse btn btn-primary"
                                                type="button">Upload</button>
                                        </span>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <img src="" alt="" width="200" id="show-image">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputUsername1">Name</label>
                            <input type="text" class="form-control" id="exampleInputUsername1" placeholder="NameProduct"
                                name="name" value="{{ old('name') }}">
                            @error('name')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPrice">Price</label>
                            <input type="text" class="form-control" id="exampleInputPrice" placeholder="price"
                                name="price" value="{{ old('price') }}">
                            @error('price')
                                <div class="text-danger">{{ $message }}</div>
                            @enderror
                        </div>
                       
                        <div class="form-group">
                            <label for="">Description</label>
                            <textarea name="description" class="form-control" id="description" value="{{ old('description') }}"></textarea>
                            @error('description')
                                <span class="text-danger">
                                    {{ $message }}
                                </span>
                            @enderror
                        </div>
                        <!-- Button trigger modal -->
                        <input type="hidden" id="inputSize" name='sizes'>
                        <button type="button" class="btn btn-primary clickmodal" data-bs-toggle="modal"
                            data-bs-target="#AddSizeModal">
                            Add size
                        </button>
                        <div class="modal" id="AddSizeModal" tabindex="-1" aria-labelledby="AddSizeModalLabel"
                            aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content p-3">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="AddSizeModalLabel">Add size</h5>
                                        {{-- <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button> --}}
                                    </div>
                                    <div class="modal-body" id="AddSizeModalBody">
                                    </div>
                                    <div class="mt-3">
                                        <button type="button" class="btn  btn-primary btn-add-size">Add</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="">Category</label>
                            <select class="form-control form-control-sm" name="category_id">
                                @foreach ($categories as $item)
                                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                                @endforeach
                            </select>

                            @error('category_ids')
                                <span class="text-danger">
                                    {{ $message }}
                                </span>
                            @enderror
                        </div>

                        <button class="btn btn-primary mr-2">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
       
        <script src="{{ asset('plugin/ckeditor5-build-classic/ckeditor.js') }}"></script>

    {{-- <script src="https://cdn.ckeditor.com/ckeditor5/38.1.0/classic/ckeditor.js"></script> --}}
    <script>
        let sizes = [{
            id: Date.now(),
            size: 'M',
            quantity: 1
        }];
        </script>
    <script src="{{ asset('admin/template/product/product.js') }}"></script>
@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Product Edit')
@section('content')
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">EDIT PRODUCT</h4>
                <p class="card-description">

                </p>
                <form class="forms-sample" method="post" action="{{ route('products.update', $product->id) }}" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6">
                                <label>Avata</label>
                                <input type="file" name="image" accept="image/*" id="image-input"
                                    class="file-upload-default">
                                <div class="input-group col-xs-6">
                                    <input type="text" class="form-control file-upload-info" disabled=""
                                        placeholder="Upload Image">
                                    <span class="input-group-append">
                                        <button class="file-upload-browse btn btn-primary"
                                            type="button">Upload</button>
                                    </span>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <img src="{{ asset('/storage/images/' . $product->image) }}" width="300" id="show-image">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputUsername1">Name</label>
                        <input type="text" class="form-control" id="exampleInputUsername1" placeholder="NameProduct"
                            name="name"  value="{{ old('name') ?? $product->name }}">
                        @error('name')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPrice">Price</label>
                        <input type="text" class="form-control" id="exampleInputPrice" placeholder="price"
                            name="price" value="{{ old('price') ?? $product->price }}">
                        @error('price')
                            <div class="text-danger">{{ $message }}</div>
                        @enderror
                    </div>
         
                    <div class="form-group">
                        <label for="">Description</label>
                        <textarea name="description" class="form-control" id="description" >{{ old('description') ?? $product->description }}</textarea>
                        @error('description')
                            <span class="text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    <!-- Button trigger modal -->
                    <input type="hidden" id="inputSize" name='sizes'  value="{{ old('size') ?? $product->size }}">
                    <button type="button" class="btn btn-primary clickmodal" data-bs-toggle="modal"
                        data-bs-target="#AddSizeModal">
                        Add size
                    </button>
                    <div class="modal" id="AddSizeModal" tabindex="-1" aria-labelledby="AddSizeModalLabel"
                        aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content p-3">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="AddSizeModalLabel">Add size</h5>
                                    {{-- <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button> --}}
                                </div>
                                <div class="modal-body" id="AddSizeModalBody">
                                </div>
                                <div class="mt-3">
                                    <button type="button" class="btn  btn-primary btn-add-size">Add</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">Category</label>
                        <select class="form-control form-control-sm" name="category_id">
                            @foreach ($categories as $item)
                            <option value="{{ $item->id }}"
                                {{ $product->category->id == $item->id ? 'selected' : '' }}>
                                {{ $item->name }}</option>

                            @endforeach
                        </select>

                        @error('category_ids')
                            <span class="text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>

                    <button class="btn btn-primary mr-2">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js"
        integrity="sha512-WFN04846sdKMIP5LKNphMaWzU7YpMyCU245etK3g/2ARYbPK9Ub18eG+ljU96qKRCWh+quCY7yefSmlkQw1ANQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="{{ asset('plugin/ckeditor5-build-classic/ckeditor.js') }}"></script>
    <script>
        let sizes = @json($product->details)
    </script>
    <script>
        let sizes = [{
            id: Date.now(),
            size: 'M',
            quantity: 1
        }];
    </script>
    <script src="{{ asset('admin/template/product/product.js') }}"></script>
@endsection

resources/views/admin/product/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Product')

@section('content')
    <div class="card">
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        <div class="card-body">
            <h4 class="card-title">Product</h4>
            <p class="card-description">
                <a href="{{ route('products.create') }}" class="btn btn-info font-weight-bold">+ Create Product</a>
            </p>
            <div class="pull-left search">
                <form>
                    <input type="search" class="form-control" placeholder="Search" name="q"
                        value="{{ $search }}">
                </form>
            </div>
            <div class="table-responsive pt-3">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                ImageProduct
                            </th>
                            <th>
                                NameProduct
                            </th>
                            <th>
                                Price

                            </th>
                            <th>
                                NameCategory
                            </th>
                            <th>
                                Action
                            </th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($products as $item)
                            <tr>
                                <td>
                                    {{ $item->id }}
                                </td>
                                <td>
                                    <img src="{{ asset('/storage/images/' . $item->image) }}" width="100">
                                </td>
                                <td>
                                    {{ $item->name }}
                                </td>
                                <td>
                                    {{ $item->price }}
                                </td>
                                <td>
                                    {{ $item->category->name }}
                                </td>

                                <td>
                                    <form action="{{ route('products.destroy', $item->id) }}" method="post">
                                        <a href="{{ route('products.edit', $item->id) }}" class="btn btn-info">Update</a>
                                        <a href="{{ route('products.show', $item->id) }}" class="btn btn-info">Show</a>
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-danger">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                <div class="btn-group mt-1" role="group" aria-label="Basic example">
                    {{ $products->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/product/show.blade.php
@extends('admin.layouts.app')
@section('title', 'Product show ' . $product->name)
@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="row card-body">
                    <h1>Chi tiết sản phẩm {{ $product->name }} - {{ $product->id }}</h1>
                    <div class="col-7">
                        <div>
                            <label for="">Tên sản phẩm : {{ $product->name }}</label>
                        </div>
                        <div class="row">
                            <div class="col-sm-4">
                                <img src="{{ asset('/storage/images/' . $product->image) }}" width="400">

                            </div>
                        </div>
                    </div>
                    <div class="col-5">
                        <div>
                            <label for="" class="text-black">Giá thành :</label> {{ $product->price }} đ

                        </div>
                        <div>
                            <label for="" class="text-black">Giá sale :</label> {{ $product->sale }} đ
                        </div>
                        <div>
                            <label for="" class="text-black">Size</label>
                            <ul>

                                @if ($product->details->count() > 0)
                                    @foreach ($product->details as $detail)
                                        <li>{{ $detail->size }} - số lượng : {{ $detail->quantity }}</li>
                                    @endforeach
                                @else
                                    <p>Sản phẩm chưa nhập size</p>
                                @endif

                            </ul>
                        </div>
                        <div>
                            <label for="" class="text-black">Loại sản phẩm</label>
                            <ul>
                                {{-- @foreach ($product->category as $item)
                                    <li>{{ $item->name }} </li>
                                @endforeach --}}
                                {{$product->category->name}}
                            </ul>

                        </div>
                        <div>
                            <label for="" class="text-black">Mô tả</label>
                            <div>
                                {!! html_entity_decode($product->description) !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endsection